import type { Corpus } from './corpus'
import { collectionDetail, collectionPaths, recordRows } from './read'
import type { FieldHint, LogEntry, RecordRow } from './types'

export interface ReadmeRenderContext {
  savedAt: string
  current?: LogEntry
  history: LogEntry[]
}

const GENERATED =
  '<!-- Generated by grove. Edit _grove/overview.md or records, then commit to refresh. -->'

function section(src: string, fallback: string): string {
  return (src.trim() ? src : fallback).trimEnd()
}

function cell(value: unknown): string {
  if (value === undefined || value === null) return ''
  const text = Array.isArray(value)
    ? value.join(', ')
    : typeof value === 'object'
      ? JSON.stringify(value)
      : String(value)
  return text.replace(/\r?\n/g, '<br>').replace(/\|/g, '\\|')
}

function linkCell(label: unknown, href: string): string {
  const text = cell(label).replace(/\]/g, '\\]')
  return `[${text}](${href.replace(/\)/g, '%29')})`
}

function changedCell(changed: LogEntry['changed']): string {
  if (!changed.length) return ''
  const shown = changed.slice(0, 6).map((c) => `${c.status} ${c.path}`)
  if (changed.length > shown.length) shown.push(`+${changed.length - shown.length} more`)
  return cell(shown.join('\n'))
}

function historyTable(ctx: ReadmeRenderContext): string {
  const rows = [...(ctx.current ? [ctx.current] : []), ...ctx.history].slice(0, 10)
  if (!rows.length) return '_No saves yet._'
  return [
    '| Saved | Commit | Message | Changes |',
    '| --- | --- | --- | --- |',
    ...rows.map((r) =>
      [
        cell(r.at || ctx.savedAt),
        cell(r.commit === 'current' ? 'current save' : r.commit.slice(0, 8)),
        cell(r.message),
        changedCell(r.changed),
      ].join(' | '),
    ),
  ]
    .map((line) => (line.startsWith('|') ? line : `| ${line} |`))
    .join('\n')
}

function recordHref(row: RecordRow, collection: string): string {
  const prefix = `${collection}/`
  return row.path.startsWith(prefix) ? row.path.slice(prefix.length) : row.path
}

function tableRule(numeric: boolean): string {
  return numeric ? '---:' : '---'
}

function dataTable(
  rows: RecordRow[],
  fields: Array<[string, FieldHint]>,
  collection: string,
): string {
  if (!rows.length) return '_No records._'
  const showStatus = rows.some((r) => r.status !== 'verified')
  const headers = ['Record', ...(showStatus ? ['Status'] : []), ...fields.map(([name]) => name)]
  const rules = [
    tableRule(false),
    ...(showStatus ? [tableRule(false)] : []),
    ...fields.map(([, hint]) => tableRule(hint.type === 'integer' || hint.type === 'number')),
  ]
  const lines = [`| ${headers.map(cell).join(' | ')} |`, `| ${rules.join(' | ')} |`]
  for (const row of rows) {
    const values = [
      linkCell(row.title, recordHref(row, collection)),
      ...(showStatus ? [cell(row.status)] : []),
      ...fields.map(([f]) => cell(row[f])),
    ]
    lines.push(`| ${values.join(' | ')} |`)
  }
  return lines.join('\n')
}

export function renderSpaceReadme(corpus: Corpus, ctx: ReadmeRenderContext): string {
  const overview = section(corpus['_grove/overview.md'] ?? '', '# Grove Space\n\nA grove space.')
  return `${GENERATED}

${overview}

## Last Save

${ctx.savedAt}

## Recent Changes

${historyTable(ctx)}
`
}

export function renderCollectionReadme(
  corpus: Corpus,
  collection: string,
  _ctx: ReadmeRenderContext,
): string {
  const detail = collectionDetail(corpus, collection)
  const overview = section(detail.overview, `# ${detail.name}\n\nA grove collection.`)
  const fields = Object.entries(detail.schema.fields)
  const rows = recordRows(corpus, collection)
  return `${GENERATED}

${overview}

## Data

${dataTable(rows, fields, collection)}
`
}

export function renderReadmeFiles(
  corpus: Corpus,
  ctx: ReadmeRenderContext,
): Record<string, string> {
  const files: Record<string, string> = {
    'README.md': renderSpaceReadme(corpus, ctx),
  }
  for (const collection of collectionPaths(corpus)) {
    files[`${collection}/README.md`] = renderCollectionReadme(corpus, collection, ctx)
  }
  return files
}
