// Generates bundled corpora for the app:
//  - generated/corpus.ts from spaces/demo  (offline seed for the live workspace)
//  - generated/help.ts   from spaces/docs  (the read-only Help panel — ships with the app)
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadCorpusFromDir } from '../packages/core/src/node'

function emit(spaceRel: string, outRel: string, exportName: string) {
  const dir = fileURLToPath(new URL(`../${spaceRel}`, import.meta.url))
  const out = fileURLToPath(new URL(`../${outRel}`, import.meta.url))
  const corpus = loadCorpusFromDir(dir)
  mkdirSync(dirname(out), { recursive: true })
  writeFileSync(
    out,
    `// AUTO-GENERATED by scripts/gen-corpus.ts — do not edit.\nimport type { Corpus } from '@grove/core'\n\nexport const ${exportName}: Corpus = ${JSON.stringify(corpus)}\n`,
  )
  console.log(`gen-corpus: ${spaceRel} → ${outRel} (${Object.keys(corpus).length} files)`)
}

emit('spaces/demo', 'packages/app/src/generated/corpus.ts', 'corpus')
emit('spaces/docs', 'packages/app/src/generated/help.ts', 'helpCorpus')
